build:
  stage: build
  tags:
    - docker
  only:
    - master
  script:
    - "docker login -u $DOCKER_USER -p $DOCKER_PASSWORD"
    - "docker build -t marhaupe/docker-react-native ."

push:
  stage: push
  when: manual
  allow_failure: false
  tags: 
    - docker
  only:
    - master
  script:
    - "docker push marhaupe/docker-react-native"

cleanup:
  stage: cleanup
  when: always
  tags:
    - docker
  only:
    - master
  script:
    - docker image prune -f

stages: 
  - build
  - push
  - cleanup
